### ISSUE TITLE
Need option to handle flagsmith init with invalid or bad token

### ISSUE THREAD

**Issue by TD-4242** [Flagsmith/flagsmith-js-client#108]
while going through and validating some operational scenarios in our application I've found that I can't pass an invalid token to flagsmith.init and have a way to gracefully recover.

![image](https://user-images.githubusercontent.com/3487671/159803661-847f3213-c4b6-4c5a-8929-5d2a5a6ce65b.png)

for example:
```
flagsmith.init({
  api: flagsmith_url,
  environmentID: 'BAD_TOKEN'
  defaultFlags,
  onChange,
})
```
I would expect this to initialize flagsmith with the contents of `defaultFlags` and be disconnected from the api server.

Also within this testing I checked having `api: 'http://badurl'` at which point flagsmith would load defaultFlags and continue.

**Comment by kyle-ssg** [comment]
Hey, 

Is it that you'd want an onChange to trigger in this scenario? Having tried the following out the SDK logs out the defaultFlags
```
flagsmith.init({
    environmentID: "badID",
    defaultFlags: {
        font_size: { value: 10 }
    },
})
console.log(flagsmith.getValue("font_size")) // logs 10
```

**Comment by TD-4242** [comment]
Interesting, let me dig a little deeper,  I've run a test with flagsmith.init({api: "badurl"}) and it did what I expected but with the "badID" everything hung up and wouldn't continue.

**Comment by kyle-ssg** [comment]
Closing as stale
