### ISSUE TITLE
Unsafe use of global flagsmith instance in Next.js example

### ISSUE THREAD

**Issue by markatom** [Flagsmith/flagsmith-js-client#111]
Hi there,

I've followed the example use of Flagsmith SDK in the Next.js application and I think the global instance of the SDK should not be used.

Suppose you have the following code in your `_app.tsx`:

```typescript
import flagsmith from 'flagsmith-es/isomorphic';

MyApp.getInitialProps = async ({ ctx }) => {
    await flagsmith.init({
        environmentID,
        identity: getIdentityFromCookies(ctx),
    });
    await new Promise((resolve) => { // simulate another asynchronous code
        setTimeout(resolve, 5000);
    });
    return {
        flagsmithState: flagsmith.getState(),
    };
};
```

Because the `flagsmith` instance is global and thus shared across all requests, one request can rewrite the data of another request. Consider the following scenario:

1. Incoming request A.
2. `getIntitialProps` of `_app.tsx` is executed.
3. Global `flagsmith` instance is initialized for request A.
4. Another asynchronous code inside `getIntialProps` is being executed.
5. Incoming request B.
6. `getIntitialProps` of `_app.tsx` is executed.
7. Global flagsmith instance is initialized for request B with a different identity (rewriting identity of request A).
9. Asynchronous code inside `getIntialProps` for request A gets finished.
10. Page for request A with incorrect feature flags and identity gets rendered and sent to the client.
11. Page for request B gets rendered and sent to the client.

I've successfully replicated this scenario locally, I can provide you working example if you want.

This may seem like a rare race condition, however, in applications with higher load (eg. 100+ requests per minute for one Node.js process) the likeliness of this could get quite high.

I suggest creation of a new instance of the SDK for each invocation of `getInitialProps` inside `_app.tsx` using `createFlagsmithInstance` and storing it into Next.js's context (`ctx`), which is designated for this purpose.

Please let me know if I've missed something or if this is a potential issue.

Thank you for a great piece of open-source software with really good documentation!

**Comment by kyle-ssg** [comment]
Hey, yeah I think I understand. So you're saying each SSR of getInitialProps can be reusing the singleton instance of flagsmith? I didn't realise that _app would be held in memory / reused like that - that's interesting to know.

I think getting a replication of the issue may be useful just so that we can consider this in future - we're big fans of Next!

**Comment by markatom** [comment]
I've updated the Next.js example in my fork here https://github.com/markatom/flagsmith-js-client/tree/unsafe-use-of-global-flagsmith-instance-in-nextjs-example/examples/nextjs. Please look at it and try it yourselves.

I've also prepared a short screen recording showing the issue.

https://user-images.githubusercontent.com/5060034/166227929-42f25b4a-2e83-47c4-8821-e1091b24196b.mov

Should I prepare a pull request with, what I consider, a correct setup for Next.js? We could discuss the details there.

**Comment by kyle-ssg** [comment]
Hey @markatom, I'm keen to catch up on this - I've cloned that branch on your repository but can't seem to replicate what you're seeing. Have you since adjusted the branch to get around the issue?

**Comment by kyle-ssg** [comment]
Ah never mind, I can see this happening now and understand https://github.com/Flagsmith/flagsmith-js-client/pull/113 would be the solution :D - this is in the latest version now so should be all good.
