### ISSUE TITLE
Dynamic Code Evaluation prevents Flagsmith to run on Next.js middlewares

### ISSUE THREAD

**Issue by cagrispan** [Flagsmith/flagsmith-js-client#112]
Hi,

I'm trying to run `flagsmith` on a Next.js middleware to load different routes depending on flags as below:

```
import flagsmith from "flagsmith/isomorphic";
import { NextRequest, NextResponse } from "next/server";

flagsmith.init({
  environmentID: {{ENVIRONMENT_KEY}},
});

export default async function middleware(request: NextRequest) {
  const url = request.nextUrl.clone();

  if (flagsmith.hasFeature(url.pathname)) {
    const UUID = crypto.randomUUID();

    await flagsmith.identify(UUID);
    url.pathname = flagsmith.getValue(url.pathname) as string;

    const response = NextResponse.rewrite(url);

    return response;
  }
}
```

It **runs locally, but fails on build** with the error:

```
./node_modules/flagsmith/index.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware

Import trace for requested module:
./pages/_middleware.ts
```

I would like to know if there is a plan to support Next.js Middlewares in the near future.

For reference:

[Edge Runtime Unsupported APIs](https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis)

------------------------------------------------------------------------------------------------------------------------------------------------------

UPDATE

The `Function` calls are added when `AsyncStorage` is used.  If you don't pass it as a parameter and build the project, it will not include any dynamic code evaluation on the index files.

```
// index.ts - line 6
const flagsmith = core({ fetch });
```

This is not a solution, just some progress on the investigation.

**Comment by alizain** [comment]
@dabeeeenster all of the flagsmith code is obfuscated and compiled. you don't provide unobfuscated source. what's the best way for us to help?

**Comment by alizain** [comment]
my bad, i couldn't find the correct file :)

**Comment by kyle-ssg** [comment]
This is now available in flagsmith 3.3.2, there's a working example [here](https://github.com/Flagsmith/flagsmith-js-client/blob/main/examples/nextjs-middleware/README.md)

**Comment by cagrispan** [comment]
Nice @kyle-ssg! Thank you!

**Comment by kyle-ssg** [comment]
No problem! I'd love to hear about what you do with it, had a play around with it today, it looks like the main use cases would be redirecting for abn tests maybe
