### ISSUE TITLE
React 18 support?

### ISSUE THREAD

**Issue by jaredmpeterson** [Flagsmith/flagsmith-js-client#115]
There are a few changes needed for flagsmith to work with react v18. Is there any timeline for these changes?

**Comment by dabeeeenster** [comment]
Hi Jared,

Are you able to share your findings and we can fix things up? Thanks! cc @kyle-ssg

**Comment by jaredmpeterson** [comment]
`Type '{ children: Element; options: { environmentID: string; }; flagsmith: IFlagsmith; }' is not assignable to type 'IntrinsicAttributes & FlagsmithContextType'.
  Property 'children' does not exist on type 'IntrinsicAttributes & FlagsmithContextType'.ts(2322)`

[The most notable change is that the children prop now needs to be listed explicitly when defining props.](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions)
