### ISSUE TITLE
Version 2.0.10 contains breaking change

### ISSUE THREAD

**Issue by mrlubos** [Flagsmith/flagsmith-js-client#118]
Hey! Just got notified by the dependency bot there's an upgrade available from 2.0.9 to 2.0.10. Running tests on that fails with the following error:

```
Failed to compile.
TS2345: Argument of type '{ environmentID: string; onChange: () => void; }' is not assignable to parameter of type 'IInitConfig'.
  Property 'angularHttpClient' is missing in type '{ environmentID: string; onChange: () => void; }' but required in type 'IInitConfig'.
 66 |     }
 67 |
> 68 |     flagsmith.init({
    |^
> 69 |       environmentID,
    |^^^^^^^^^^^^^^^^^^^^
> 70 |       onChange: () => {
    |^^^^^^^^^^^^^^^^^^^^
> 71 |         onDone();
    |^^^^^^^^^^^^^^^^^^^^
> 72 |       },
    |^^^^^^^^^^^^^^^^^^^^
> 73 |     });
    |^^^^^^
 74 |   }, [init, setFeatureFlags]);
 75 |
 76 |   useEffect(() => {
error Command failed with exit code 1.
```

As you can see, Flagsmith expects the property `angularHttpClient` to exist. However, I am not even in Angular project, so this shouldn't be an issue.

**Comment by kyle-ssg** [comment]
Hey @mrlubos, this is now fixed in flagsmith,flagsmith-es and react-native-flagsmith @3.0.3. As a note v3 is just to mark that the SDK now points to the global edge API (which means you should see faster response times outside EU) - I'd suggest upgrading to this 🙂
