### ISSUE TITLE
Upgrading Flagsmith examples to use latest version of library

### ISSUE THREAD

**Issue by piyushchauhan2011** [Flagsmith/flagsmith-js-client#128]
Currently, flagsmith example of `react` is still using the 2.x version. Do we have any plans to upgrade the example to 3.x version of flagsmith which uses the edge api ?

<img width="679" alt="Screen Shot 2565-07-10 at 20 37 40" src="https://user-images.githubusercontent.com/693487/178147300-30509d2a-d694-4df8-9132-429269db643f.png">

**Comment by dabeeeenster** [comment]
Ah yep good catch - @kyle-ssg PR submitted for approval #129

**Comment by piyushchauhan2011** [comment]
Awesome, thank you :)
