### ISSUE TITLE
Flagsmith: Fetch error: ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by nvsd** [Flagsmith/flagsmith-js-client#135]
Created the issue in the wrong repo https://github.com/Flagsmith/flagsmith/issues/1385

When building an SSR app (locally and vercel.com) I get the error `Flagsmith: Fetch error: ReferenceError: XMLHttpRequest` is not defined.

It's just a warning too so it doesn't block me or anything just slightly annoying.

To repro clone and yarn build in the below repo:
https://github.com/nvsd/flagsmith-repro

**Comment by nvsd** [comment]
@dabeeeenster Sorry about that.

This issue should make quite a bit more sense here!

**Comment by kyle-ssg** [comment]
Hey @nvsd.

Thanks for submitting an issue, there were a few adjustments you needed to make in order to get this to work. I've noted them in a pull request I've made to your example.


https://github.com/nvsd/flagsmith-repro/pull/1


> - With SSR and technologies such as next you should use flagsmith/isomorphic which deals with a mixture of node and frontend
> - Since fetching flags is asynchronous you'd need to either show a loader on SSR or more ideally await fetching flags, I've added the latter in MyApp.getInitialProps
> - In relation to the above, we can use the SSR data from Flagsmith to prevent fetching on the client if we want you could add in the like preventFetch: !!flagsmithState in the options object
