### ISSUE TITLE
`typeof window !== 'undefined'` breaks persistence in React Native

### ISSUE THREAD

**Issue by elliottkember** [Flagsmith/flagsmith-js-client#137]
There are a few places in `flagsmith-core.ts` that check for `typeof window!=='undefined'` before using AsyncStorage:

https://github.com/Flagsmith/flagsmith-js-client/blob/9bc1a595b6b30597bfdde9bdb0107122b1a74be9/flagsmith-core.ts#L359

`window` is undefined in React Native, which means that persistence does not work.

`window` is not used inside any of those blocks, so it's unclear to me what purpose these window checks serve.  Fortunately, when we removed them with a patch everything seems to work fine, and persistence works!

**Comment by kyle-ssg** [comment]
Thanks for reporting, I'll have to test this PR as this was intentional in order to support SSR frameworks. With some of these, AsyncStorage is defined however their implementation cannot work when running from Node.

**Comment by kyle-ssg** [comment]
This should be fixed in 3.9.2, please re-open if you believe this is not the case.
