### ISSUE TITLE
Real time flags need to hit 2 separate domains/services

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith-js-client#142]
When streaming real time flags, we need the JS SDK to connect to the normal Edge API for regular flags etc as per default, but then it needs to connect to `realtime.flagsmith.com` to stream realtime updates. 

We should also be able to override the `realtime_api_url` domain name if self hosting real time flags or for local testing etc. 

Also we need to change line https://github.com/Flagsmith/flagsmith-js-client/blob/17f5cd19ae2d346f5ae4323b95ac7263d22b14c8/flagsmith-core.ts#L252 to use the domain name `realtime.flagsmith.com`

**Comment by kyle-ssg** [comment]
Currently, you can pass in eventSourceUrl to flagsmith.init() to configure the realtime URL. So I think this already achieves this, I think from the description we just need to change the default URL to be realtime.flagsmith.com ?
