### ISSUE TITLE
React-Native - Calling flagmisth.init on a device without internet connection breaks with  'Cannot read property 'flags' of undefined'

### ISSUE THREAD

**Issue by gfrancischini** [Flagsmith/flagsmith-js-client#148]
**How to reproduce**
Using a iOS simulator turn off the internet and call `flagmisth.init`.

The `onError` method will be called with the following message: `'Cannot read property 'flags' of undefined'`

It seems that the code is not prepare to handle lack of internet connection

Version: 3.10.2

**Comment by kyle-ssg** [comment]
I'll try and replicate this - but from what I can see the only references to flags are from this.flags, indicating that this is undefined.

If I can't replicate it I may ask for an example repro.

**Comment by kyle-ssg** [comment]
Ok, yep could replicate this, the problem is that this was overwriting storage rather than ignoring failed network requests.

I've updated this in 3.11.0, you can run the example react-native app that caches for offline. You can now go offline in this example and it'll revert successfully to cache.

**Comment by kyle-ssg** [comment]
Thanks very much for reporting this!
