### ISSUE TITLE
defaultFlags: Property 'id' is missing in type '{ enabled: true; }' but required in type 'IFlagsmithFeature'.ts

### ISSUE THREAD

**Issue by franciscohanna92** [Flagsmith/flagsmith-js-client#153]
I'm trying to provide default values for my feature flags  (following the [docs](https://docs.flagsmith.com/clients/javascript/#providing-default-flags)) but I have a Typescript error:
```
Property 'id' is missing in type '{ enabled: true; }' but required in type 'IFlagsmithFeature'.ts(2741)
```
The error is present both in the method `flagsmith.init` and in the `options.defaultFlags` props for the `FlagsmithProvider` in the React SDK. I'm using flagsmith `3.13.0`

![image](https://user-images.githubusercontent.com/12707758/199548418-e2ffffce-517c-4873-9c90-bb6d3c10d964.png)

As a workaround I'm just setting random number IDs for each flag, but I'm not sure if this has some unexpected consequences. 

I guess a solution would be to have the `id` property as optional in the `IFlagsmithFeature` interface. Would you accept a PR for this?

**Comment by kyle-ssg** [comment]
Reviewing this, it does look like id is still needed under the hood - so yeah happy to accept this as being optional. Thanks!

**Comment by kyle-ssg** [comment]
id is now optional in 3.13.1 - thank you very much for raising

**Comment by franciscohanna92** [comment]
@kyle-ssg Thanks a lot!
