### ISSUE TITLE
Calling getAllFlags from useFlagsmith in react throws an error

### ISSUE THREAD

**Issue by tm1000** [Flagsmith/flagsmith-js-client#154]
TypeError: Cannot read properties of undefined (reading 'flags')

```js
const { getAllFlags } = useFlagsmith();
console.log(getAllFlags());
```

Works
```js
console.log(flagsmith.getAllFlags());
```

**Comment by tm1000** [comment]
I actually have the same issue when trying to use `identify`

TypeError: Cannot set properties of undefined (setting 'identity')
```js
const { identify } = useFlagsmith();
await identify('abc')
```

**Comment by kyle-ssg** [comment]
I believe that's because that is trying to destructure a class instance, and the context is not right.

The following will work:

```
const flagsmith = useFlagsmith()
flagsmith.identify('abc')
```
