### ISSUE TITLE
TypeError: Cannot convert undefined value to object - when calling getOwnPropertyNames in analyticsFlags()

### ISSUE THREAD

**Issue by joshea0** [Flagsmith/flagsmith-js-client#155]
We are seeing this exception in our production environment in our react native application:

```
TypeError: Cannot convert undefined value to object
  at getOwnPropertyNames(app:///main.jsbundle)
  at anonymous(node_modules/react-native-flagsmith/index.js:1:4499)
  at apply(app:///main.jsbundle)
  at anonymous(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:231:13)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:112:15)
  at callTimers(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:357:17)
  at apply(app:///main.jsbundle)
  at __callFunction(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:417:5)
  at anonymous(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:114:7)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:11)
  at callFunctionReturnFlushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:5)
```

Based on the information we are seeing in Sentry for the exception, it is coming from `node_modules/react-native-flagsmith/index.js` on this line:

```
        if (this.evaluationEvent && Object.getOwnPropertyNames(this.evaluationEvent).length !== 0 && Object.getOwnPropertyNames(this.evaluationEvent[this.environmentID]).length !== 0) {

```

We did not see this error in development or when testing our app in production mode in TestFlight.

We are using `react-native-flagsmith` version `3.10.2`

We do not have a clean reproduction for it, but that isn't surprising since this seems to be coming from a timer tick from setInterval (if I'm reading the SDK code correctly). Sentry has reported this happening to over 3000 users though.

Any ideas what could be causing this and/or suggestions on how to fix or debug it?

**Comment by joshea0** [comment]
Looking at the line of code in question more closely...

It checks if `this.evaluationEvent` is truthy before  calling `Object.getOwnPropertyNames(this.evaluationEvent)`. However, it does not do the same for `this.evaluationEvent[this.environmentID]`.

This suggests perhaps `this.evaluationEvent[this.environmentID]` is undefined, and since there is no check to guard against it we get this error. Perhaps the fix is adding a check for `this.evaluationEvent[this.environmentID]`. So the line would become:

```
        if (this.evaluationEvent && Object.getOwnPropertyNames(this.evaluationEvent).length !== 0 && this.evaluationEvent[this.environmentID] && Object.getOwnPropertyNames(this.evaluationEvent[this.environmentID]).length !== 0) {

```

Of course I don't have much context for what the SDK is intending to do here, so this is just an educated guess based on the pattern I'm seeing there.

**Comment by joshea0** [comment]
I just checked out version `3.14.1` and I see this check was added in that function:

```js
if (!this.evaluationEvent|| !this.evaluationEvent[this.environmentID]) {
    return
}
```

I assume that was intended to fix this problem? If so, then please feel free to close this issue and we will upgrade our SDK to 3.14.1

**Comment by kyle-ssg** [comment]
Hi @joshea0 - you're correct! This fixed an issue where people were switching between environments, analytics was failing in this instance but it wouldn't have affected fetching flags.
