### ISSUE TITLE
Consider updated_at timestamp with SSE

### ISSUE THREAD

**Issue by kyle-ssg** [Flagsmith/flagsmith-js-client#162]
Related: https://github.com/Flagsmith/edge-proxy/issues/47

updated_at will now include a timestamp, the SDK should only retrieve flags if the updated_at value is greater than the current value.

The current value will be based on the timestamp at the point of making a new request.

```
event: environment_updated
data: {'updated_at': 1673546928.02806}
retry: 15000
```

gz#436

**Comment by dabeeeenster** [comment]
This is not working in beta 10:

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/173290/222141069-35e061ce-f455-44de-a0b2-4adaabb3f4b3.png">

![Uploading image.png…]()
