### ISSUE TITLE
3.18.0 breaks tests with EventSource ReferenceError

### ISSUE THREAD

**Issue by cbix** [Flagsmith/flagsmith-js-client#165]
After updating to 3.18.0 (which seems to not be in `master` yet), our tests (using jest) are failing with
```
    ReferenceError: EventSource is not defined

    > 1 | import flagsmith from 'flagsmith';
        | ^
```
Apparently one solution would be to add testing mocks for `EventSource`, however this is a breaking change not usually expected on a minor release. Since 3.16.0 also used `EventSource` without these issues, I assume it's simply a bug anyway.

gz#495

**Comment by kyle-ssg** [comment]
Hi @cbix, since flagsmith is never intended to be used in a NodeJS context (vs flagsmith/isomorphic which is) but yes I think for jest this shouldn't simply throw an exception. 

This should be resolved in 3.18.1, though please re-open if you have any issues.
