### ISSUE TITLE
isLoading never updates to false if flag is disabled (React useFlagsmith hook)

### ISSUE THREAD

**Issue by Marlon-Buckley** [Flagsmith/flagsmith-js-client#174]
Hello! 

I came into an issue today trying to use the `.isLoading` property on the `useFlagsmith()` hook. In short, I have a React component as below, keep in mind the root of the app is wrapped in your neat `<FlagsmithProvider />` :

```
import React, { useEffect } from 'react';
import { useFlags, useFlagsmith } from 'flagsmith-es/react';

export default function Home() {
	const flagsmith = useFlagsmith();
	const { first_feature } = useFlags(['first_feature']);

	useEffect(() => {
		document.title = 'Home';
	}, []);

	if (!flagsmith.isLoading) {
		return (
			<>
				<h1>Home page</h1>
				{first_feature.enabled && (
					<p>{flagsmith.identity} has first_feature flag enabled🎉</p>
				)}
			</>
		);
	}
}
```

In this example, if the `first_feature` flag is disabled on the console for the user then the `.isLoading` property never changes from true to false. As such I can't use `.isLoading` as I'd hoped to!

If the `first_feature` flag is enabled on the console, the `.isLoading` property updates as I would expect, and is set to false on the second render.

Is this the intended use/behaviour of `.isLoading` ? I came across this PR https://github.com/Flagsmith/flagsmith-js-client/pull/169 apologies if this is something you're already aware of! 

Any help would be much appreciated!

**Comment by Marlon-Buckley** [comment]
Following up on this. I discovered that If I have another flag inside `useFlags()`, and if that flag is always enabled in the Flagsmith console, the `isLoading` property behaves as I'd expect. 

```
export default function Home() {
	const flagsmith = useFlagsmith();
	const flags = useFlags(['first_feature', 'foo']);

	useEffect(() => {
		document.title = 'Lantern';
	}, []);

	if (!flagsmith.isLoading) {
		return (
			<>
				{flags.first_feature.enabled && (
					<p>{flagsmith.identity} has first_feature flag enabled🎉</p>
				)}
				<h1>home page</h1>
			</>
		);
	}
}
```
So in this version, the `first_feature` flag is disabled on the Flagsmith console and the `foo` flag is enabled. `flagsmith.isLoading` starts out as false, then changes to true and finally ends up false as I'd expect.

**Comment by kyle-ssg** [comment]
Hey @Marlon-Buckley, isLoading was actually intended just for internal use at this time, hence why it wasn't referenced in our docs. We do have plans for adding a strategy for loading state as it's a bit more complex than just isLoading when you consider cache and default flags.

Please refer to https://github.com/Flagsmith/flagsmith-js-client/pull/169, if it interests you I could publish a beta for this to see if it fits your usecase?

**Comment by vik-buchinski** [comment]
@kyle-ssg Hello!
Any progress or deadline for releasing https://github.com/Flagsmith/flagsmith-js-client/pull/169 ?

Thanks in advance!

**Comment by kyle-ssg** [comment]
Apologies for the silence on this @Marlon-Buckley @vik-buchinski, I've tested internally and am happy with the current PR. I'll be getting this reviewed by our team, in the meantime there is a beta version on npm - 3.18.5-beta7
