### ISSUE TITLE
Don't call getFlags() if the identity set is the same

### ISSUE THREAD

**Issue by strugee** [Flagsmith/flagsmith-js-client#177]
I want to set up our React app so that I can unconditionally identify to Flagsmith on every authenticated page load. This means that Flagsmith will use the proper identity even if users e.g. refresh the page and therefore enter the app through a route that we wouldn't typically consider an "entry point". The problem with this is that Flagsmith will call `getFlags()` every time a page navigation occurs, resulting in a lot of unnecessary requests. I could work around this by setting some global state in React, but this is super annoying given the way React thinks about state and I don't really want to bother with it.

It would be much nicer if I could just unconditionally call `identify()`, on basically every render, and have Flagsmith just do the Right Thing™ and make it a no-op _unless_ the identity actually changed.

**Comment by strugee** [comment]
> It would be a major breaking change if we made it default behaviour...

Hmm, how so? I mean, I suppose if you're relying on this side effect instead of just calling `getFlags()` you'd be broken... but why would you do that in the first place?

**Comment by strugee** [comment]
It's also possible this is the wrong layer to provide this at - it might make more sense to have a wrapper at the Flagsmith React integration layer that used this proposed behavior. The idea being that hey, use this React integration wrapper because it makes it easy to deal with this network side effect thing in the context of a React app.

**Comment by dabeeeenster** [comment]
> It's also possible this is the wrong layer to provide this at - it might make more sense to have a wrapper at the Flagsmith React integration layer that used this proposed behavior. The idea being that hey, use this React integration wrapper because it makes it easy to deal with this network side effect thing in the context of a React app.

Q for @kyle-ssg and @novakzaballa !

**Comment by kyle-ssg** [comment]
I don't think the React layer is the right place to do it, as the suggested behaviour has nothing to do with React. If we were to make any changes I think it'd be part of the core library.

Making identify skip the API makes sense, the only use-case I think is weird would be if the identity was already the same as the result of cache rather than a previous API response. That's the only part I'd see as a nasty breaking change.
