### ISSUE TITLE
Provide explicit setter functions for Data Dog / Dynatrace

### ISSUE THREAD

**Issue by kyle-ssg** [Flagsmith/flagsmith-js-client#181]
In an SSR based application we cannot initialise and track RUM events on the server, this means that when the client hydrates we are not calling the corresponding dtrum and datadogrum functions, see https://github.com/Flagsmith/flagsmith-js-client/blob/main/flagsmith-core.ts#L171

We should separate the above out into functions setDtrum and setDatadogRum so they can be called when mounting the frontend in frameworks such as Next.js

**Comment by novakzaballa** [comment]
@kyle-ssg are there any specifics and details you can add as well as acceptance criteria, so I can address this request?
For example: Is there any existing DataDog example integration that I could use to test the integration with a SSR NextJS app?

**Comment by kyle-ssg** [comment]
This is no longer an issue
