### ISSUE TITLE
[Bug] - NextJS >= 13.0.0 SSR `useFlagsmith` state not matching the state that is passed to the provider.

### ISSUE THREAD

**Issue by joelpierre** [Flagsmith/flagsmith-js-client#186]
I am using the NextJS SSR example for implementation and have ran into issues when working locally with the hook states not matching what is fetched in CustomApp.getInitialProps and then passed down to the FlagsmithProvider.

My expectation here is that all SSR components using the hook will leverage the state I have fetched in the initial CustomApp fetch (which is correct), what I am seeing however is that it seems to be just responding with an old version of the flag state.

Below (responses reduced so you can see the specific issue) is what comes back for my flags when I console out the `useFlagsmith` response in a component on the server

```js
{
  flagsmith: {
   ...
    flags: { editorial_plp: { id: 56935, enabled: true, value: 'on' } },
   ...
  }
}
```

and the same console log on the client console is:

```js
{
  flagsmith: {
    flags: {
      editorial_plp: { id: 56935, enabled: true, value: 'on' },
      shop_pay_button: { id: 58185, enabled: true, value: null }
    },
    ...
  }
}
```

and my flagsmithSSR log (server side)

```js
{
  flagsmithSSR: {
    flags: {
      editorial_plp: { id: 56935, enabled: true, value: 'on' },
      shop_pay_button: { id: 58185, enabled: true, value: null }
    },
    ...
  }
}
```

As you can see the first is not a reflection of all my feature flags

**Comment by kyle-ssg** [comment]
Hey, @joelpierre. Could I see the getInitalProps code / FlagsmithProvider Initialisation? 

by "flagsmithSSR" log I assume you mean a console log directly after the flagsmith.initialise or identify await?

**Comment by joelpierre** [comment]
> Hey, @joelpierre. Could I see the getInitalProps code / FlagsmithProvider Initialisation?
> 
> by "flagsmithSSR" log I assume you mean a console log directly after the flagsmith.initialise await?

Yeah `flagsmithSSR` is after flagsmithInstance.init(...) etc. Code below

```ts
...
// flagsmith/util.ts

export const flagsmithClientInstance = async (userUUID?: string) => {
  const flagsmithInstance = createFlagsmithInstance()
  await flagsmithInstance.init({
    environmentID: process.env.NEXT_PUBLIC_FLAGSMITH_CLIENT_KEY!,
    identity: userUUID,
  })
  return flagsmithInstance
}

// _app.tsx - getInitialProps
...
const flagsmithSSR = await flagsmithClientInstance(userUUID)
console.dir({ flagsmithSSR },  { depth: null })

return {
   ...
   flagsmithState: flagsmithSSR.getState(),
   ...
}
...

// CustomApp render

...
<FlagsmithProvider flagsmith={flagsmith} serverState={flagsmithState}>
...

```

The entire app is wrapped in the correct data and when I console.log the flagsmithState passed from getInitialProps it has the correct info but the hook value doesn't 😅

**Comment by kyle-ssg** [comment]
I'm assuming shop_pay_button only comes back for the identified user? 

At some point there must be an API call that results in no "shop_pay_button" as the hook wouldn't randomly miss looking up flag state.

I'll look at the above and attempt to replicate your scenario.

**Comment by joelpierre** [comment]
its on for everyone in our env as seen in the screen shot

![Screenshot 2023-09-27 at 22 53 24](https://github.com/Flagsmith/flagsmith-js-client/assets/8969851/7bc2b8cb-956e-4d71-873c-ade09ba8cc2b)

The issue is when I turn off the local dev server and turn it back on the correct data is returned, so my steps were:
- Started local dev
- Created new feature flag
- Refresh my app and got hydration warnings for server side render not matching client side render
- logged out different things and saw that the hook returns different info to what the SSR getState() func returns and doesn't return what is fed into the provider
- rebooted the local dev server
- issue resolved

The reason I am worried is that if I deploy the app it won't "restart" until a new deployment or if serverless restarted that way I guess? which means there could be a significant amount of time before my next "restart".

**Comment by kyle-ssg** [comment]
Ah, right, I see. So, in that case was flagsmith.init actually even called on the Server? My guess is it wasn't and the hydration issue is as expected.

**Comment by joelpierre** [comment]
The logs from `flagsmithSSR` were correct but the hook rendered in a component lower down the component tree was not correct and was showing older data 🤔

**Comment by kyle-ssg** [comment]
It feels like there's some sort of weird NextJS caching here of SSR and this isn't actually down to what Flagsmith is doing. 

I wonder if the SSR render that came back when you refreshed was the result of cache? I'll play around and try turning off cache with devtools open if I can replicate.

**Comment by joelpierre** [comment]
Nice one thanks Kyle, thats a good shout 🤔 are you using native fetch under the hood? I know they've tampered with that guy 😅

**Comment by kyle-ssg** [comment]
Ha yeah I've experienced a bug with that on a project recently now that you mention it. The isomorphic client does use built in fetch yeah.

**Comment by kyle-ssg** [comment]
I can confirm that on the example (though using probably older Next 12.1) This issue is not occurring, I'll try on a later version


![](http://g.recordit.co/tRIUecEQZB.gif)

**Comment by kyle-ssg** [comment]
Ok I think I understand the issue.

As of Next 13 variables remain in memory in SSR within _app.tsx. 

So the flagsmith import that's being used in <Flagsmith provider is being used across multiple sessions. Previously in Next 12, reloading the page would execute the code in _app.

I think the following will ensure everything works as expected.

```
    const flagsmithRef = useRef(createFlagsmithInstance())
    return (
        <FlagsmithProvider flagsmith={flagsmithRef.current}
```

**Comment by joelpierre** [comment]
Man... are you assuming its the additions to the fetch API? Could you update the packaged to set the revalidate to 0?

```
...await fetch(`https://...`, {
    next: { revalidate: 0 },
  })
```

We are on version 13.4.4.

So with your workaround is 
```
const flagsmithRef = useRef(createFlagsmithInstance())
    return (
        <FlagsmithProvider flagsmith={flagsmithRef.current}
```

the same as using `flagsmith` from `import flagsmith from 'flagsmith/isomorphic';` and passing that to the flagsmith prop?

**Comment by kyle-ssg** [comment]
Hey no I don’t think it’s the fetch api at all it’s more that code in _app doesn’t get executed per session anymore. Did you check if the above works for you ? I think it should since it creates a singleton in the render as a ref

**Comment by kyle-ssg** [comment]
It is yeah, guarantees a single instance since it’s a ref and gets executed where as anything outside the component doesn’t get evaluated per session. If you put a console log outside of the app component you’ll see, in next 12 it’d log each time.

**Comment by kyle-ssg** [comment]
I also don’t know if there’s a better solution than the workaround, we’d want to guarantee a separate singleton per ssr session. I wouldn’t be surprised if this difference between next 12 and 13 trips a lot of libraries up

**Comment by joelpierre** [comment]
Yeah I imagine it would totally. Glad I didn't raise a dud issue for you 😅

Happy to contribute and update the docs if you need help.

**Comment by kyle-ssg** [comment]
Thanks for the offer and raising this! I've put in a PR for updating the NextJS example and the docs
