### ISSUE TITLE
[Bug] - TypeError: Cannot read properties of null (reading 'getValue')

### ISSUE THREAD

**Issue by joelpierre** [Flagsmith/flagsmith-js-client#189]
Currently seeing the below, I think there may be some guard clauses missing before calling "getValue"

```
TypeError: Cannot read properties of null (reading 'getValue')
    at /var/task/node_modules/.pnpm/flagsmith@3.19.1/node_modules/flagsmith/react.js:1:1616
    at Array.map (<anonymous>)
    at c (/var/task/node_modules/.pnpm/flagsmith@3.19.1/node_modules/flagsmith/react.js:1:1581)
    at e.useFlags (/var/task/node_modules/.pnpm/flagsmith@3.19.1/node_modules/flagsmith/react.js:1:2458)
```

**Comment by novakzaballa** [comment]
Hi @joelpierre, can you please provide more details and context about this issue, including how can we reproduce it?

**Comment by joelpierre** [comment]
Hey, it turns out it was very bespoke to our setup with server side Algolia not playing ball, however it would be great if in your SDK the useFlag hook didn't do this

```ts
const res = useMemo(() => {
        const res: any = {}
    flags.map((k) => {
        res[k] = {
                enabled: flagsmith!.hasFeature(k),
                value: flagsmith!.getValue(k),
        }
    }).concat(traits?.map((v) => {
        res[v] = flagsmith!.getTrait(v)
    }))
```

As you can see the `flagsmith!` which is what is blowing up for us. Not sure if you can change these to `flagsmith?.` ...

**Comment by dabeeeenster** [comment]
Hey again, I think maybe we could, however I'm not sure what instances would exist where the Flagsmith Providers don't get a Flagsmith instance. Was there a good example that I'm maybe not understanding?

**Comment by kyle-ssg** [comment]
Hey again, I think maybe we could, however I'm not sure what instances would exist where the Flagsmith Providers don't get a Flagsmith instance. Was there a good example that I'm maybe not understanding?

**Comment by joelpierre** [comment]
With Algolia SSR they want you to do some pretty weird and wonderful things for server side rendering as you can see here: https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react/#with-nextjs and as a result we have to pre-render the Algolia listing "stuff" server side and renderToString... in essence all our _app providers are not loaded in this serverState until hydration kicks in on the client.

It would be good if flagsmith didn't blow up though haha as I went down a rabit hole debugging it 😬 . OR if there was more of a check to ensure the provider state was set before trying to do anything further?

**Comment by novakzaballa** [comment]
Hi there, could you please include a sample minimal project failing, and a clear description of what would be the expected behavior?

**Comment by novakzaballa** [comment]
We're going to close this issue due to inactivity. Please feel free to reopen it if you have the required information.
