### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by dementors-magnus** [Flagsmith/flagsmith-js-client#198]
The LICENSE-file says BSD 3-Clause and package.json says MIT. It would be great it was consistent as it facilitates using license compliance tools.

**Comment by novakzaballa** [comment]
Hi @dementors-magnus, thank you for bringing this to our attention. We will take a look and prioritize it in consequence.

**Comment by dementors-magnus** [comment]
Thank you for a quick response! 👍
