### ISSUE TITLE
Typing issue in react.tsx: 'flagsmith' is possibly 'null'

### ISSUE THREAD

**Issue by davinov** [Flagsmith/flagsmith-js-client#202]
Hello, and thanks for you awesome work on Flagsmith :clap: 

I've encountered a small issue raised by the TypeScript checker when using the react lib.
It seems that the case where `flagsmith` is not set is not handled here: https://github.com/Flagsmith/flagsmith-js-client/blob/main/react.tsx#L41

I've fixed it by just adding a `?`:
```
--- a/node_modules/flagsmith/src/react.tsx
+++ b/node_modules/flagsmith/src/react.tsx
@@ -111,7 +111,7 @@ export function useFlagsmithLoading() {
     }
 
     useEffect(() => {
-        if (!subscribed && flagsmith.initialised) {
+        if (!subscribed && flagsmith?.initialised) {
             events.on('loading_event', eventListener)
             setSubscribed(true)
         }
```
Does that seem the correct fix to you?
If yes, I can of course open a small PR for this.

**Comment by matthewelwell** [comment]
Hi @davinov thanks for this. I think that the link you included is pointing to a different line of code than the one you mentioned in the fix? 

I'm not overly familiar with the JS client so I'm waiting for one of our other engineers to respond, but I'd be interested to know if there is a particular scenario you have identified where `flagsmith` is not set? I would imagine this to always be set. Perhaps it's a typing issue further down the line for example? Should `useContext` ever not return a valid instance of `flagsmith`?

**Comment by davinov** [comment]
Thanks for your quick reply

You're right about the line, my mistake!
The same condition is repeated twice in this file:
- once in `FlagsmithProvider` L41: this seems OK because there the `flagsmith` argument is of type `IFlagsmith`, and not optional
- once in `useFlagsmithLoading` L114, which gets `flagsmith` from the context `useContext(FlagsmithContext)`. In that case, it seems that it could be null because of the intiialization value of the context (`export const FlagsmithContext = createContext<IFlagsmith<string,string> | null>(null)`

So another possibility would be to change the initialization value to a "default" flagsmith instance. However, that instance would not have any of important the parameters expected to be set by the consumers of the package, such as `api` or `environmentID`, so I guess this second option seems less appropriate to me.

I'll try to make a minimal reproduction repo this evening if I can spare some time.

**Comment by davinov** [comment]
When creating a new repo, I've noticed that my import of `flagsmith/react` was mistaked. My IDE imported automatically `flagsmith/src/react` instead :facepalm: 
That included your source code to our typechecking, instead of relying on the exposed types (the `.d.ts` files).

You may still want to fix the error that raises when developing your client though, if you got some time :)
![Screenshot from 2023-11-23 01-24-16](https://github.com/Flagsmith/flagsmith-js-client/assets/932583/5ce77213-2f95-4783-915e-aea4dcb52ac2)

Thanks again for the quick reply, and sorry for the noise
