### ISSUE TITLE
useFlags not updating values in react18/Nextjs App Router

### ISSUE THREAD

**Issue by kyle-ssg** [Flagsmith/flagsmith-js-client#214]
I believe https://github.com/Flagsmith/flagsmith-js-client/pull/188 attempted to solve this, however the following project does not see new values for useFlags https://github.com/Flagsmith/flagsmith-js-examples/pull/8. Essentially in the current live version of the SDK  events.off('event', eventListener) is removing more than 1 event handler.

To get around it, the PR has a version of flagsmith from https://github.com/Flagsmith/flagsmith-js-client/pull/210/files#diff-090ff4f85a594b9bd7b6f1a515395bd0a604ade2c55db3e5c9e7ea76021cbd7fL156 that fixes the issue, but it'd cause a leak due to the removed line.

I cannot figure out the issue, however maybe we need to implement a version of tinyevents that lets you remove the exact event listener that you setup.

i.e. 

```

const remove = events.on('x'...

return ()=> remove()

```

**Comment by benjiekibblewhite** [comment]
Oh fabulous! I just found this bug myself on version 3.19.01, and was about to post an issue when I realized I should probably check to see if someone else reported it first... Thank you!
