### ISSUE TITLE
Flags are null when the cacheFlags option is true

### ISSUE THREAD

**Issue by dawiidio** [Flagsmith/flagsmith-js-client#220]
Hey,

most likely I found a bug that blocked our implementation. Below is the configuration we are using, I want the flags to be saved for 24h in local storage, unfortunately what I get in the first argument of onChange is null instead of flags, the same thing happens in the useFlag hooks. In local storage I can see the values in under the BULLET_TRAIN_DB key.

This is config:

```ts
{
  environmentID: FLAGSMITH_CLIENT_SIDE_API_KEY,
   cacheFlags: true,
   cacheOptions: {
     ttl: hoursToMilliseconds(24),
     skipAPI: true,
   },
   onChange(a, b, c) { 
     console.log('onchange', a, b, c); // a is null
   }
}
```

Flagsmith version: `"flagsmith": "^3.23.2",`

here what I see in LS and what onChange logs

![Screenshot 2024-03-08 at 21 27 37](https://github.com/Flagsmith/flagsmith-js-client/assets/7998389/890b3977-dcda-4497-b342-b449cfbc9137)

Could you help us with this?

**Comment by kyle-ssg** [comment]
Hi, the first argument of onChange is the previous flags, as can be seen [here](https://docs.flagsmith.com/clients/javascript/#initialisation-options), the previous flags would be null unless you provided flag defaults. To get the current flags you would use the flagsmith SDK.

As for useFlags not having any value, I'll try and replicate this and get back to you however I'd expect it to contain the flags from cache. e.g.

```
const {test} = useFlags(["test])
```

**Comment by kyle-ssg** [comment]
Given the following on flagsmith: "^3.23.2" I can see useFlags being populated with cache, so I may need more information.


```
//App
ReactDOM.render(
  <FlagsmithProvider options={{
      environmentID: "QjgYur4LQTwe5HpvbvhpzK",
      cacheFlags: true,
      cacheOptions: {
        ttl: 10000000,
        skipAPI: true,
      },
      onChange(a, b, c) {
        console.log('onchange', a, b, c); // a is null
      }
  }} flagsmith={flagsmith}>
    <App />
  </FlagsmithProvider>,
  document.getElementById('root')
);

```


```
// HomePage
function App() {
    const flags = useFlags(['font_size']); // only causes re-render if specified flag values / traits change
    return (
        <div className='App'>
            font_size: {flags.font_size?.value}
        </div>
    );
}
```

Output:

<img width="102" alt="image" src="https://github.com/Flagsmith/flagsmith-js-client/assets/8608314/64c3cdb2-45bc-4394-9859-624db5aba494">

**Comment by kyle-ssg** [comment]
Hey @dawiidio , hopefully the above clarifies things. If there's still an issue please re-open this and I'll take a look.
