### ISSUE TITLE
Identifier/trait confusion when using `cacheOptions: { skipAPI: true } `

### ISSUE THREAD

**Issue by rolodato** [Flagsmith/flagsmith-js-client#227]
Using a slightly-modified version of the React example here, I can reproduce the issue below https://github.com/Flagsmith/flagsmith-js-examples/compare/main...rolodato:flagsmith-js-examples-repro-17cf4148:main

I'm not sure what's going on here exactly, but you can see in some conditions we are using cached traits from a previous identity and inserting them into an unrelated identity. Identity `B` should never have a `name: "A"` trait set.

https://github.com/Flagsmith/flagsmith-js-client/assets/829698/8999a85d-d0e3-42d8-afd6-4b2d96172e73

**Comment by kyle-ssg** [comment]
@rolodato I believe this is resolved please start again with new identities without traits using flagsmith@4.0.2-beta-1

**Comment by matthewelwell** [comment]
Yes, I've tested and the new version seems to have resolved the issue 👍
