### ISSUE TITLE
Uncaught (in promise) Error: Cannot read properties of undefined (reading 'flags')

### ISSUE THREAD

**Issue by henriquekuwai** [Flagsmith/flagsmith-js-client#234]
Hello,

I'm experiencing some intermittent console errors on my app, which is currently using the 4.0.2 version of `flagsmith` lib.

The error is shown below:
![image](https://github.com/Flagsmith/flagsmith-js-client/assets/81972770/bbe17c07-4c4c-46fb-a9a2-e2439986feaa)

It is not something that really impacts the experience because the flags are correctly loaded, but is annoying because it is creating many error logs on our front-end monitoring service.

I reproduced the issue in a stackblitz app here: https://stackblitz.com/edit/stackblitz-starters-t4htj6?file=src%2FApp.tsx

And recorded a video with this behavior:

[Screencast from 03-07-2024 14:19:15.webm](https://github.com/Flagsmith/flagsmith-js-client/assets/81972770/70218cbf-af71-4dac-82e6-9f0d060200bc)

When I change the identity of the user (using `flagsmith.identify` method) more than once in a short time, the console error appears. Note that when I change the identity slowly, it doesn't happen. At first, I thought that was something related to the `cacheFlags` parameter, but it happens even when it is disabled.

I've tested with React 17 and 18 using FlagsmithProvider, and with both versions, it happens.

If you need more information, please let me know.

Thanks!

**Comment by dabeeeenster** [comment]
Thanks! We'll take a look.

**Comment by kyle-ssg** [comment]
Thanks for bringing this to our attention. 

This occurred when the SDK gets a response from an identity that does not match the current. You're correct that it doesn't affect the correct flags loading.

The [following PR](https://github.com/Flagsmith/flagsmith-js-client/pull/235) will resolve this. In the meantime, 4.0.3-beta-1 resolves this if you'd like to try it out. Thanks again!

**Comment by henriquekuwai** [comment]
> Thanks for bringing this to our attention.
> 
> This occurred when the SDK gets a response from an identity that does not match the current. You're correct that it doesn't affect the correct flags loading.
> 
> The [following PR](https://github.com/Flagsmith/flagsmith-js-client/pull/235) will resolve this. In the meantime, 4.0.3-beta-1 resolves this too if you'd like to try it out. Thanks again!



> Thanks for bringing this to our attention.
> 
> This occurred when the SDK gets a response from an identity that does not match the current. You're correct that it doesn't affect the correct flags loading.
> 
> The [following PR](https://github.com/Flagsmith/flagsmith-js-client/pull/235) will resolve this. In the meantime, 4.0.3-beta-1 resolves this too if you'd like to try it out. Thanks again!

It solved the problem here! Thank you :rocket:

**Comment by kyle-ssg** [comment]
This is now released in [4.0.3](https://github.com/Flagsmith/flagsmith-js-client/tree/4.0.3)

**Comment by kyle-ssg** [comment]
This is now released in version [4.0.3](https://github.com/Flagsmith/flagsmith-js-client/releases/tag/4.0.3), thanks again!
