### ISSUE TITLE
Default flags not used

### ISSUE THREAD

**Issue by eddiejaoude** [Flagsmith/flagsmith-js-client#237]
Discussion started in Flagsmith's Discord [here](https://discord.com/channels/517647859495993347/1261207488452366336/1261428729276796948)

I am trying to use the default flags for automated testing on CI, but they don't seem to be getting used, is there anything else I need to configure?

```js
  await flagsmith.init({
    environmentID: process.env.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID,
    defaultFlags: {
      tagline: {
        enabled: true,
        value: "==== TAGLINE",
      },
      news: {
        enabled: true,
        value: "----- NEWS",
      },
    },
  });
 ```

Here is the actual code 
https://github.com/EddieHubCommunity/HealthCheck/blob/23d35eef3210cf07c6200e5a1c1b833cb1b485f3/src/config/flagsmith.js#L14-L17

I tried removing the environment id and also making it incorrect, as well as setting an invalid api url, but that still didn't trigger the default flags

All testing done in private browsing using the docs https://docs.flagsmith.com/clients/javascript#providing-default-flags

**Comment by eddiejaoude** [comment]
Dan from the EddieHub community found the issue, the `init` needs to be wrapped in a try/catch so that the defaults are used.

Here are his changes
https://github.com/EddieHubCommunity/HealthCheck/pull/26/files#diff-6b595e154402ce55eda1c06e86c85ba6ad056332cfacf435af2e92e10e66abe9R14-R22

Let me know if you would like the docs updated to reflect this or otherwise just close this issue.

**Comment by dabeeeenster** [comment]
Hey @eddiejaoude - thanks for figuring this out! If you have some time to add to the docs that would be much appreciated 👍

**Comment by eddiejaoude** [comment]
Thanks for merging
