### ISSUE TITLE
Failed to parse source map from '****/angular-fetch.ts' file: Error: ENOENT: no such file or directory, open '/***/angular-fetch.ts'

### ISSUE THREAD

**Issue by vik-buchinski** [Flagsmith/flagsmith-js-client#239]
The source maps starting from version 4.0.0 are broken.
What I have in the logs:

`
WARNING in ../../node_modules/flagsmith/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/vik.buchinski/Documents/github/utils/angular-fetch.ts' file: Error: ENOENT: no such file or directory, open '/Users/vik.buchinski/Documents/github/utils/angular-fetch.ts'

WARNING in ../../node_modules/flagsmith/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/vik.buchinski/Documents/github/utils/async-storage.ts' file: Error: ENOENT: no such file or directory, open '/Users/vik.buchinski/Documents/github/utils/async-storage.ts'

WARNING in ../../node_modules/flagsmith/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/vik.buchinski/Documents/github/utils/get-changes.ts' file: Error: ENOENT: no such file or directory, open '/Users/vik.buchinski/Documents/github/utils/get-changes.ts'

WARNING in ../../node_modules/flagsmith/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/vik.buchinski/Documents/github/utils/set-dynatrace-value.ts' file: Error: ENOENT: no such file or directory, open '/Users/vik.buchinski/Documents/github/utils/set-dynatrace-value.ts'

WARNING in ../../node_modules/flagsmith/react.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/vik.buchinski/Documents/github/utils/emitter.ts' file: Error: ENOENT: no such file or directory, open '/Users/vik.buchinski/Documents/github/utils/emitter.ts'

webpack compiled with 5 warnings (ee8a793b344e9aca)
`

**Comment by matthewelwell** [comment]
Hi @vik-buchinski, please can you provide some more information here? Can you confirm exactly what steps you're taking to see these errors, and how they manifest? It seems like they are just warnings at the moment rather than errors so I'm interested to know what effect this is having.

**Comment by vik-buchinski** [comment]
@matthewelwell TBH, I didn't test the flagsmith after I saw these warnings. I just reverted to version 3 and warnings disappeared.

But anyway, there is some issue with sourcemaps in the flagsmith library version 4, it can't point from 1 file to another correctly, and instead goes to 2-3 levels higher than the root of the project to look for the .ts files that are located in the node-modules.

**Comment by matthewelwell** [comment]
Ok, thanks @vik-buchinski - we'll take a look into it.

**Comment by matthewelwell** [comment]
Ok, thanks for this @abadi-avela, we'll take a look into it this week.

**Comment by kyle-ssg** [comment]
Apologies for the late reply, there is now a PR linked that fixes this. In the meantime, I've published flagsmith@7.0.3-beta.1 which resolves that issue.

**Comment by kyle-ssg** [comment]
This is now released under version 8.0.1 🚀
