### ISSUE TITLE
When `cacheFlags` is enabled, the cached `traits` value is not updated even when new values are passed to `init`

### ISSUE THREAD

**Issue by pedroalves0** [Flagsmith/flagsmith-js-client#242]
It looks like it's the same problem reported in https://github.com/Flagsmith/flagsmith-js-client/issues/157, but for `traits` key instead of `identity`. 

Our use case is the following:

1. The flagsmith agent is first initialized with a certain user language as trait. Let's called it `lang`.
2. The user changes the app language, which triggers a reload.
3. When the Flagsmith agent is re-initalized, this time with `lang` set to the new language, Flagsmith overlooks the updated value and keeps using the cached data stored in the `BULLET_TRAIN_DB`.

From what I can see, the solution should be to extend [this condition](https://github.com/Flagsmith/flagsmith-js-client/blob/main/flagsmith-core.ts#L407-L409) so that it also applies to traits.

**Comment by novakzaballa** [comment]
Hi @pedroalves0, we’ll take a look and get back to you as soon as possible.

**Comment by henningmu** [comment]
Hi @novakzaballa do you have an update for us on this? Should we be using the SDK differently?

**Comment by novakzaballa** [comment]
I am handing off this issue to @kyle-ssg

**Comment by pedroalves0** [comment]
I confirm that the problem is fixed in `4.0.4-beta.1`. Thanks for your help @kyle-ssg ! I'll keep an eye on when the fix gets deployed to main.

**Comment by kyle-ssg** [comment]
Published under 4.1.1! Thank you very much for testing / responding to the issue
