### ISSUE TITLE
load cache value even if the ttl expired

### ISSUE THREAD

**Issue by blackjid** [Flagsmith/flagsmith-js-client#250]
I'm using `cacheFlags: true` to rapidly load the flagsmith state first thing when my page is loaded.

I'd like to define a `ttl` and `skipAPI: true` to reduce the amount of requests the flagsmith api. But still have the benefit of having the state loaded from the cache.

One option I'd like to see would be something like `cacheOptions: { loadStale: true }`, in this case:
- The cached state is loaded
- The sdk fetch from the server as normal based on the `ttl` and the `skipAPI` options.

Do you think this is something would benefit others. ~I can make a PR with a implementation I've been working on.~

Update: I went head and open a PR

**Comment by kyle-ssg** [comment]
Ah, yes that does make sense! Thank you for the suggestion!
