### ISSUE TITLE
Problem with interface in release 6.0

### ISSUE THREAD

**Issue by oluizcarvalho** [Flagsmith/flagsmith-js-client#259]
I identified this problem when trying to build version 6.0 of the library, but I had the following error:

![Image](https://github.com/user-attachments/assets/fabc9771-2dc9-4df5-817e-3263f57756c7)

I took a look at the cause of the problem and identified this change that was made to release 6.0

![Image](https://github.com/user-attachments/assets/b2ae4b19-b7cb-49cb-836c-75f0a8757108)

Could you please upload a patch fixing this issue, looking forward to testing the improvements in version 6.0

**Comment by oluizcarvalho** [comment]
if you can take a look @kyle-ssg

**Comment by oluizcarvalho** [comment]
@khvn26 @kyle-ssg The problem has not yet been resolved, release 7.0.1 does not have the changes from version 6

**Comment by matthewelwell** [comment]
Hi @oluizcarvalho, that's correct, unfortunately we had to do some version juggling due to an issue found by one of our customers. I recommend pinning to version 6 until we can re-release the changes to the latest version which we're hoping to do next week.

**Comment by oluizcarvalho** [comment]
@matthewelwell any feedback on this point?

**Comment by matthewelwell** [comment]
@oluizcarvalho v7.0.2 has been released which fixes the issue.

**Comment by oluizcarvalho** [comment]
right, but it doesn't have the code for release 6.0.0 that I contributed

**Comment by matthewelwell** [comment]
I see, yes, that's true. 

Unfortunately we are currently stuck on our releases for reasons outside of our control. I cannot bring in the code from 6.0.0 until likely December this year. I'm very sorry about that, and we'll look to get it solved as soon as we can.

**Comment by oluizcarvalho** [comment]
Okay, could you release a correction version of 6. I mean, release 6.0.1 correcting this point that is giving an error today, it would help us a lot to have a stable version working?

**Comment by oluizcarvalho** [comment]
unfortunately 6.0.0 is not working
