### ISSUE TITLE
`getFlags` removes identity identifier in evaluation context

### ISSUE THREAD

**Issue by jhoermann** [Flagsmith/flagsmith-js-client#262]
In the current flagsmith version 7.0.1 the identity identifier gets reset within the `getFlags` backend call:

![Image](https://github.com/user-attachments/assets/01381303-8ad2-4740-9683-14aa7dbcc2d6)

1. log is during init -> the identifier is set
2. log is after `getFlags` / init backend call -> identifier is lost in evaluation context

This results in `setContext` to fail because the identifier is missing:

![Image](https://github.com/user-attachments/assets/5dfcc971-68d0-4e42-ab26-aa2650b2e3b6)

**Comment by matthewelwell** [comment]
Hi @jhoermann, thanks for raising this. I think I understand the issue that you're describing, but it would be very helpful for us if you are able to share a minimal example to reproduce it?

**Comment by jhoermann** [comment]
Yes here: https://stackblitz.com/edit/flagsmith-bug-setcontext?file=main.js. As you can see the identifier is being stripped from the context @matthewelwell.

**Comment by matthewelwell** [comment]
Great, thanks for sharing that @jhoermann - we'll take a look into this and get it fixed up.

**Comment by jhoermann** [comment]
I opened up a PR - have a look @matthewelwell: https://github.com/Flagsmith/flagsmith-js-client/pull/263. Still need to verify that this solves the issue and need to add a test for it though.

**Comment by khvn26** [comment]
Hello @jhoermann — we have identified an error in the backend that caused this issue and deployed the fix. We've observed correct behaviour in the reproduction StackBlitz you'vde provided. Please confirm whether the fix is working for you.

**Comment by jhoermann** [comment]
Yes that resolves the issue as the identifier now gets returned by the backend endpoint @khvn26 @matthewelwell.

**Comment by Roma-Potapov** [comment]
Hello, I have same problem, but in my company we use self-hosted flagsmith, and we can't just update to the newest version, so can we reopen PR of @jhoermann to fix this problem on the client side

**Comment by kyle-ssg** [comment]
This is now released under version 8.0.1 🚀
