### ISSUE TITLE
getFlags removes identity identifier in evaluation context

### ISSUE THREAD

**Issue by Roma-Potapov** [Flagsmith/flagsmith-js-client#269]
As it was mention in this [issue](https://github.com/Flagsmith/flagsmith-js-client/issues/262), I have the same problem, but I use self-hosted version and can't just update it for all services. So I suggest to reopen this [PR](https://github.com/Flagsmith/flagsmith-js-client/pull/263) to fix problem on the client side

**Comment by matthewelwell** [comment]
Hi @Roma-Potapov , that seems like a reasonable request. We have re-opened the PR and hope to include it in the next release.

**Comment by kyle-ssg** [comment]
The PR mentioned is now released as part of 8.0.1, please let me know if there are any further issues 🚀 !
