### ISSUE TITLE
Flag cache not retrieved in no network conditions

### ISSUE THREAD

**Issue by KanziHanzi** [Flagsmith/flagsmith-js-client#272]
Hey there,

I'm having trouble with the caching of flags in react-native-flagsmith package.

"react-native": "0.73.8"
"react-native-flagsmith": 7.0.2
"@react-native-async-storage/async-storage": ^2.1.0

This is my implementation of the FlagsmithProvider, I can verify that an item is set to async storage called `BULLET_TRAIN_DB` to cache the flags and traits. However when I simulate a no-network condition or any sort of API failure, the locally stored item `BULLET_TRAIN_DB` is not retrieved, hence falling back to defaultFlags values instead of the cached ones.

My theory: The FlagsmithProvider is calling the `init` method but if there is no network the promise rejects and completely ignores the local cache.

````
<FlagsmithProvider
      options={{
        api: FLAGSMITH_URL,
        environmentID: FLAGSMITH_ENV,
        cacheFlags: true,
        AsyncStorage: AsyncStorage,
        cacheOptions: {
          ttl: 60000, // recreate cache after 1 minute
          skipAPI: true, // don't fetch flags from API if cache available
        },
        defaultFlags: {
          buy_flow: {enabled: false},
          sell_flow: {enabled: true},
          kyc_flow: {enabled: true},
          lightning: {enabled: false},
          lightning_onboarding: {enabled: false},
          lightning_swap: {enabled: false},
          kyc_deadline_block: {enabled: false},
        },
        evaluationContext: {
          identity: {identifier: store.user.address3},
        },
      }}
      flagsmith={flagsmith}
    >
````

Please let me know if you need more information to evaluate my issue.

**Comment by rolodato** [comment]
Could it be that your cache is expiring? You could try setting `cacheOptions.loadStale: true`

**Comment by KanziHanzi** [comment]
Hey @rolodato, already tried various configuration options including `loadStale: true` with a very large `ttl` or even completely without, always the same symptom.

**Comment by KanziHanzi** [comment]
Does anyone have an idea? Locally cached flags are quite important for our usecase to be reliable

**Comment by rolodato** [comment]
@KanziHanzi Just to be sure, could you share a full sample that we could use to reproduce the issue?

**Comment by KanziHanzi** [comment]
@rolodato What do you mean exactly by "full sample"? The FlagsmithProvider set up above is probably the only really relevant part. Besides that we're only setting a few traits here and there throughout the app. In any way the problem appears when the `init` call (from the FlagsmithProvider) fails, which then in turn doesn't read async storage to get the cache values

**Comment by KanziHanzi** [comment]
Besides that it would also be helpful to update the example implementation here: https://github.com/Flagsmith/flagsmith-js-examples/tree/main/reactnative
as it's using flagsmith version 3 instead of 7 which is the latest

**Comment by rolodato** [comment]
We'll take a look at updating those docs. I'd like to see an end-to-end sample that I can use to reproduce this issue, as I've been unable to so far.

**Comment by KanziHanzi** [comment]
I'd love to help you on that but I don't fully understand how an end-to-end sample looks like? Is there a certain example to follow on what exactly to provide?

**Comment by rolodato** [comment]
I'm referring to a runnable sample that reproduces the problem, instead of only a code snippet: https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff (not my writing, but the ideas still apply)

**Comment by KanziHanzi** [comment]
Hey @rolodato, after some deep dive and testing on a fresh repo the caching does seem to work. So the issue lies within my project somewhere.

Anyways I'll close this issue, thanks for the help!
