### ISSUE TITLE
Polling restart and interval changing issue

### ISSUE THREAD

**Issue by miscgithub** [Flagsmith/flagsmith-js-client#37]
Hi there,

I just started using bullet train with a self-hosted server and so far it's a great, smooth and fun to use tool :-)

However, I stumbled across two issues with updating/restarting polling intervals (client version 0.2.5).

**Expected behavior:**

1. Repeated calls to startListening() update the poll interval
2. After calling stopListening(), a call to startListening() will restart polling

**Observed behavior:**

1. The update interval from the initial call continues to apply
2. After calling stopListener(), polling will not resume on startListening()

**How to reproduce:**

Note: Uncomment if clause for case 2.

```javascript
    onChange: (oldFlags, params) => {
      var interval = bulletTrain.getValue('feature_flags_update_interval') || 60000
      if (interval !== currentListeningInterval) {
        // if (oldListeningInterval > 0) {
        //   bulletTrain.stopListening()
        // }
        if (interval > 0) {
          bulletTrain.startListening(interval)
        }
        currentListeningInterval = interval
      }
    }
```

Is there anything I'm doing wrong here or is this a bug?

Thanks and best regards,
Michael

**Comment by kyle-ssg** [comment]
Hey @miscgithub appologies for the late reply. You are correct on this, the client will now clear old intervals and initialise a new one regardless.

Fixed in 1.1.2 of flagsmith/react-native-flagsmith
