### ISSUE TITLE
Trait names converted to lower case on retrieval

### ISSUE THREAD

**Issue by miscgithub** [Flagsmith/flagsmith-js-client#39]
Hi there,

it seems the client converts all trait names to lower case. On the server trait names are dispayed correctly (case sensitive).

**Expected Behavior**

bulletTrain.setTrait('camelCase', 'foo')
bulletTrain.getTrait('camelCase') => 'foo'
bulletTrain.getTrait('camelcase') => undefined

**Observed Behavior**

bulletTrain.setTrait('camelCase', 'foo')
bulletTrain.getTrait('camelCase') => undefined
bulletTrain.getTrait('camelcase') => 'foo'

THanks and best regards,
Michael

**Comment by dabeeeenster** [comment]
Thanks for the report @miscgithub - we'll look into a new version that lowercase's the getTrait method.

**Comment by miscgithub** [comment]
Hi Ben, thanks for the quick response! A short thought on this: I wonder if lowercasing trait names is the best approach as the web frontend says "Trait names are case sensitive" (e.g. in "New Segment" modal). Chances are probably minor that there will be two different traits with the same lowercase representation, but it feels strange to me consistency-wise (and like a possible source of confusion) to have trait names that are case sensitive on the API level/frontend level but not on the client level. But I agree, lowercasing trait names might help in nearly all cases.

**Comment by kyle-ssg** [comment]
Hey @miscgithub, @dabeeeenster.

The flagsmith client itself currently parses response of flags and traits from the api, forcing them to lowercase. The only part that was missing was to do the exact same for the key in getTrait, getValue and hasFeature.

This means that although the api does treat them as case sensitive the sdk will rule out any possibility of case differences.


I'm going to bump this one to 1.2.0 just incase there are side effects but I think this will be fine.

1.2.0 is now released for both flagsmith and react-native-flagsmith.
