### ISSUE TITLE
Typescript type definition file does not have a default export.

### ISSUE THREAD

**Issue by lehmamic** [Flagsmith/flagsmith-js-client#47]
It is not possible to import the flagsmith module from the npm package in Angular 11, which compiles to ES6 due to a missing default export.

`import flagsmith from 'flagsmith';`

will cause following error:
`Module '"flagsmith"' has no default export.`

Anyway, your index.d.ts does not really reflect you javascript code base. In reality you have a default export a constant of a class which you also should mirror in the index.d.ts

**Comment by kyle-ssg** [comment]
Hey @lehmamic, thanks for the report!

Fixed in 1.1.1 of  flagsmith/react-native-flagsmith.
