### ISSUE TITLE
TypeScript breaking change in version 1.4.0

### ISSUE THREAD

**Issue by mrlubos** [Flagsmith/flagsmith-js-client#73]
The version 1.4.0 was meant to add an optional parameter to the `identify()` method like `identify(userId:string, traits?: Record<string, string|number|boolean>)`, but the actual type is [`identify(userId:string, traits: Record<string, string|number|boolean>)`](https://github.com/Flagsmith/flagsmith-js-client/blob/master/flagsmith/index.d.ts#L62) which leads to compiler crashing when simply upgraded from version 1.3.0

**Comment by kyle-ssg** [comment]
Ah yep, typo on my end should be fixed in 1.4.1
