### ISSUE TITLE
Add changelog or releases?

### ISSUE THREAD

**Issue by mrlubos** [Flagsmith/flagsmith-js-client#74]
Hey! I think it would be useful to provide a changelog or a release list on Github so it's easy to see what has changed since the last version. I have just opened [this issue](https://github.com/Flagsmith/flagsmith-js-client/issues/73) and the way I caught that was by first looking at the version difference which had no release info, then I went into our build logs to see what crashed, and finally to the Flagsmith source code to find the offending code. Beyond the obvious benefits of change history, it changelog could be useful to faster pinpoint any potential breaking changes in the future

**Comment by kyle-ssg** [comment]
Sure, makes sense. Apologies for the issue you faced, see https://github.com/Flagsmith/flagsmith-js-client/releases

**Comment by mrlubos** [comment]
> Sure, makes sense. Apologies for the issue you faced, see https://github.com/Flagsmith/flagsmith-js-client/releases

No problem, thank you for the quick fix!
