### ISSUE TITLE
onError not firing when no envrionment id is specified

### ISSUE THREAD

**Issue by sammysium** [Flagsmith/flagsmith-js-client#75]
Perhaps I am wrong but I was under the impression that when there is an error initalizing flagsmith, the onError call back is called. Here is my step, which on purpose doesn't have envrionment Id.

handleFlagsError has logic depending on the envrionment that I want to confirm with a unit test. The following is the code:

```
const handleFlagsError = (e) => {
  console.log('reached error handler');
};

const initializeFlagSmith = () => {
   flagsmith.init({
    environmentID: Config.FS_ENVID,
    api: 'url',
    asyncStorage: AsyncStorage,
    cacheFlags: true,
    onError: handleFlagsError,
    defaultFlags: TabletConfigurations
  });
  flagsmith.startListening(30000);
};
```

now I understand envrionment ID is required but i am not seeing logs in my console. Now in my test I am doing:
```
Config.FS_ENVID = undefined;
initializeFlagSmith();
```

I don't see console from handleFlagsError but I do see Please specify a environment id which is thrown out I believe by flagsmith itself. I was hoping to see simply:

`    'reached error handler'`

hope I made sense.

**Comment by kyle-ssg** [comment]
Hey @sammysium, sure that makes sense. I'll look at having it trigger the onError too, this was originally intended for errors during flag retrieval but I see your point.

**Comment by sammysium** [comment]
the fix seems good enough for now @kyle-ssg thanks so much.
