### ISSUE TITLE
getFlags() , identify(), setTrait(), setTraits() Promise doesn't return a value when resolved. Returns undefined

### ISSUE THREAD

**Issue by Nihir10dec** [Flagsmith/flagsmith-js-client#81]
```
flagsmith.getFlags()
.then((res) => console.log(res))
.catch((err) => console.log(err));
```
This prints out as ``undefined``
The exact same thing is happening with all the functions which internally calls ``getFlags()`` like ``identify(), setTrait(), setTraits()``.

I can see the API call in the network tab and it is successful with the proper flags returned. But the value doesn't resolve in the promise returned by any of the functions.

I am first calling ``flagsmith.init()`` and then ``flagsmith.identify()``

**Comment by kyle-ssg** [comment]
Could I ask what the usecase here is, @Nihir10dec? The idea is to use flagsmith calls such as getValue/hasFeature calls and these calls resolve after the flags and traits has been retrieved.

I’m not really sure what we would want to resolve with if anything.

**Comment by Nihir10dec** [comment]
So my use case is to get all the Flags at the point where I call the ``identify()`` function, so that I retrieve all the flags according to the identified user.
As there are a lot of features and it's a large project where I'm using, calling each features ``getValue()`` can be just redundant work.
Hence to retrieve all the flags at just once, I wanted the values returned from the promise.

**Comment by harenlewis** [comment]
Hey, @kyle-ssg Any thoughts or suggestions on this?

**Comment by kyle-ssg** [comment]
getValue / hasFeature is pretty much exactly the same as doing flags[name]. These calls do not interact with the api.

The approach should still be as I mentioned, if we started to resolve a set of flags with these calls it would encourage not using these functions which allow flag analytics and any other future features.

**Comment by kyle-ssg** [comment]
Considering the above, the types have been updated to indicate that getFlags etc do not resolve with flags
