### ISSUE TITLE
TS type broken for React Native

### ISSUE THREAD

**Issue by marcshilling** [Flagsmith/flagsmith-js-client#82]
In this commit: https://github.com/Flagsmith/flagsmith-js-client/commit/a7ef16ab821e804e472889ee30fe1ae25c68ccff

You can see the TS declaration was changed from `react-native-flagsmith` to just `flagsmith`. Now `import flagsmith from 'react-native-flagsmith'` fails to pick up the types.

**Comment by kyle-ssg** [comment]
Ah thanks for reporting, fixed in 1.6.1 @marcshilling
