### ISSUE TITLE
identify() return type is Promise<IFlags>, but after npm install version 1.7.2, the return type there is Promise<null>

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith-js-client#91]
identify() return type is Promise<IFlags>, but after npm install version 1.7.2, the return type there is Promise<null>. It seems the package was not released properly.

**Comment by kyle-ssg** [comment]
This is simply not the case. identify does return Promise<null>. Promise<lFlags> was incorrect, it shouldn't be used that way. [See here](https://github.com/Flagsmith/flagsmith-js-client/issues/81)
