### ISSUE TITLE
Reference to Bullet Train

### ISSUE THREAD

**Issue by oguzhanogreden** [Flagsmith/flagsmith-js-client#92]
It looks there's a rogue reference to "Bullet Train" [here](https://github.com/Flagsmith/flagsmith-js-client/blob/67319456fc1d2eb554547e905d326e5e342baf40/index.d.ts#L36).

**Comment by dabeeeenster** [comment]
@kyle-ssg there are actually many references to Bullet Train both in the source and places like `package.json`

**Comment by kyle-ssg** [comment]
Will review this. 

Since the types were written before the rebrand we'd probably just deprecate the BulletTrain types and roll a major version as this would be a breaking change.

**Comment by kyle-ssg** [comment]
Where possible this has been done, details of remaining instances can be seen [here](https://github.com/Flagsmith/flagsmith-js-client/pull/94). This is deployed under flagsmith@1.7.3 and react-native-flagsmith@1.7.3
