### ISSUE TITLE
Possible inconsistency in IBulletTrainFeature and getValue() declarations

### ISSUE THREAD

**Issue by oguzhanogreden** [Flagsmith/flagsmith-js-client#95]
Hi,

I'm a bit puzzled by the following (type) declarations.

```ts
declare class IFlagsmith {
    ...
    /**
     * Returns the current flags
     */
    getAllFlags:()=> IFlags

    /**
     * Get the value of a particular remote config e.g. flagsmith.getValue("font_size")
     */
    getValue:(key: string) => string|number|boolean
    ...
```

If I understand it correctly:

- `getAllFlags()` will return the flags
- (Given that there's a flag among them with key `buttonSize` and value `1`) `getValue(buttonColor)` will return `1`.
- According to the type declaration, this is expected.

_Notice the inline documentation of `getValue()` is inconsistent in its terminology choice with the description [here](https://docs.flagsmith.com/clients/node#available-functions): "remote config" and "feature"._

---

I believe `IBulletTrainFeature` is supposed to represent flags that we receive from you, see `onChange()` and `getAllFlags()`.

Relevant type declarations are:

```ts
export interface IFlags {
    [key: string]: IBulletTrainFeature
}
```

and

```ts
export interface IBulletTrainFeature {
    enabled: boolean
    value?: string
}
```

---

If this all makes sense... `getValue()` and `IBulletTrainFeature.value` should be referring to the same entity. If I got that correct, I don't see how they can have different types.

And indeed... if I set a feature flag like below, it comes back as a `number` rather than a `string`:
![image](https://user-images.githubusercontent.com/7797029/150157469-c4fce51f-2dc6-41d4-b36b-cb2ad77f0671.png)

**Comment by kyle-ssg** [comment]
Right, yep you're correct. value should equally be string|number|boolean.

Will adjust this and put out a release later today.

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith-js-client/commit/10ab4d13314efc72b966886993282173e922543c

This has been fixed, it was actually already this before the issue was raised.

**Comment by oguzhanogreden** [comment]
I'm confused because of [this](https://github.com/Flagsmith/flagsmith-js-client/blob/10ab4d13314efc72b966886993282173e922543c/flagsmith/index.d.ts#L3), which is the client I'm using I believe.

**Comment by oguzhanogreden** [comment]
Type declarations aren't DRY enough and that's causing this maybe?
