### ISSUE TITLE
Undocumented error: "Exception fetching evaluationEvent ReferenceError: state is not defined"

### ISSUE THREAD

**Issue by oguzhanogreden** [Flagsmith/flagsmith-js-client#96]
Hey there, it's me again!

I'm testing your JS client in one of our Angular (v11) apps. For testing purposes, I've initialized the client with logging turned on.

I get the following error logged into the console repeatedly:
```
FLAGSMITH: 40194 ms Exception fetching evaluationEvent ReferenceError: state is not defined
```

I can see that this error message is printed [here](https://github.com/Flagsmith/flagsmith-js-client/blob/00b92fb874f208b5ca0482ae806cbcc933928954/flagsmith-core.js#L136-L151) in your source.

My first priority is to understand whether this has any functional implications. I've checked the network tab of my developer tools report to see what's happening with that request.

Roughly at the same with this error, I see POST request to `/analytics/flags` returns a 200. It has the expected request payload (as far as I can tell). The response body is empty. So it seems to be fine, I guess?

I've figured I'd turn off analytics to see if that'd help. I seem to be getting this error regardless of the `enableAnalytics` parameter of the `init()` method. Is that parameter not respected?

I'm happy to provide more details from my side if you need that.

**Comment by kyle-ssg** [comment]
Hi, could you provide a minimal code example for this? 

The error in question seems very peculiar since the only reference to state is above the post request, the post request seems to be happening and the variable declaration is just above. 

As for seeing this when you disable analytics, this may be the case just for the first time whilst it has remaining events exist in local storage.

**Comment by oguzhanogreden** [comment]
(I'm trying to have some time to look into this. It wasn't possible so far as I can't copy paste our application code into Stackblitz 😬 )

**Comment by kyle-ssg** [comment]
Closing this, please feel free to re-open if this is still an issue
